# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attendee(object):
    def setupUi(self, Attendee):
        Attendee.setObjectName("Attendee")
        Attendee.resize(800, 600)
        Attendee.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(Attendee)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 410, 211, 51))
        self.pushButton_2.setStyleSheet("border: 1px solid black;\n"
"font: bold 18px;\n"
"font-family: Arial;\n"
"color: black;\n"
"background-color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(700, 500, 91, 81))
        self.nextButton.setStyleSheet("border: none;")
        self.nextButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../EVO/New_design/Ui_Files/images/NextArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon)
        self.nextButton.setIconSize(QtCore.QSize(100, 100))
        self.nextButton.setObjectName("nextButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 210, 471, 191))
        self.label_2.setStyleSheet("border: 1px solid black;\n"
"font: bold 18px;\n"
"font-family: Arial;\n"
"color: black;\n"
"background-color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 490, 111, 101))
        self.backButton.setStyleSheet("border: none;")
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../EVO/New_design/Ui_Files/images/BackArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(100, 100))
        self.backButton.setObjectName("backButton")
        self.nextButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton_2.setGeometry(QtCore.QRect(10, 500, 91, 81))
        self.nextButton_2.setStyleSheet("border: none;")
        self.nextButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton_2.setIcon(icon2)
        self.nextButton_2.setIconSize(QtCore.QSize(100, 100))
        self.nextButton_2.setObjectName("nextButton_2")
        Attendee.setCentralWidget(self.centralwidget)

        self.retranslateUi(Attendee)
        QtCore.QMetaObject.connectSlotsByName(Attendee)

    def retranslateUi(self, Attendee):
        _translate = QtCore.QCoreApplication.translate
        Attendee.setWindowTitle(_translate("Attendee", "MainWindow"))
        self.pushButton_2.setText(_translate("Attendee", "Add CSV FILE"))
        self.label_2.setText(_translate("Attendee", "csv_file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attendee = QtWidgets.QMainWindow()
    ui = Ui_Attendee()
    ui.setupUi(Attendee)
    Attendee.show()
    sys.exit(app.exec_())
